version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
      - run:
          name: Run script
          command: |
            . venv/bin/activate
            python main.py

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
